config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'issues#search'
  get '/home/jira', to: 'home#jira'
  get '/dailyreports/owner_dailyreport/:id', to: 'dailyreports#owner_dailyreport', :as => 'my_crs'

  resources :projects
  resources :issues
  resources :issue_types
  resources :owners
  resources :dailyreports

  # Devise routes
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  devise_for :users
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in')
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :project
  belongs_to :owner
  has_many :dailyreport_issues, dependent: :destroy
  has_many :dailyreports, through: :dailyreport_issues
  max_paginates_per 10

  before_create { |issue| issue.jiraid = issue.jiraid.upcase }
  validates :jiraid, format: { with: /\b[a-zA-Z]{2,6}-[1-9]\d{0,3}\b/, message: 'must follow this format ABCXYZ-9999' }
  validates :jiraid, uniqueness: true

  validates :jiraid, :project, :owner, :time_forecast, :time_real, presence: true

  validates :time_real, numericality: { only_float: true }
  validates :time_forecast, numericality: { only_float: true }
end

app/models/issue_type.rb
class IssueType < ApplicationRecord
  before_create { |issue_type| issue_type.name = issue_type.name.capitalize }

  validates :name, uniqueness: true
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  require 'net/http'
  require 'uri'

  before_action :define_issue, only: [:show, :edit, :update, :destroy]
  before_action :admin_only_access, only: [:destroy, :edit, :update]

  def index
    @issues = Issue.all.order(created_at: :desc).page params[:page]
  end

  def search
    if params[:search].blank?
      redirect_to issues_path and return
    else
      @parameter = params[:search].downcase
      @results = Issue.all.where('lower(jiraid) LIKE :search', search: "%#{@parameter}%").page params[:page]
    end
  end

  def new
    @issue = Issue.new
  end

  def show
    call_jira_api("https://agenceinspire.atlassian.net/rest/api/3/issue/#{@issue.jiraid}")
    if @response_output_issues.key?('errors')
      flash.alert = "Please check if #{@issue.jiraid} exists and is available on JIRA"
      no_api_reponse
    else
      issue_details_from_jira(@issue)
      yes_api_response
    end
  end

  def create
    @issue = Issue.new(issue_params)

    # Check if issue exists on JIRA
    unless call_jira_api("https://agenceinspire.atlassian.net/rest/api/3/issue/#{@issue.jiraid}")
      flash.alert = "Please check if #{@issue.jiraid} exists and is available on JIRA"
    end

    # Get issue details from JIRA
    issue_details_from_jira(@issue)
    issue_time_real_from_jira(@issue)

    # Save the issue
    if @issue.save
      flash.notice = "Issue #{@issue.jiraid} created"
      redirect_to issues_path and return
    else
      flash.alert = "There was a problem saving #{@issue.jiraid}, check if all the fields are filled on the JIRA issue"
    end
  end

  def edit
  end

  def update
    if @issue.update(issue_params)
      redirect_to issues_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if current_user.admin?
      @issue.destroy
    else
      admin_only_access
    end
    previous_page
  end

  private

  def issue_params
    params.require(:issue).permit(
      :jiraid,
      :project_id,
      :owner_id,
      :time_forecast,
      :time_real,
      :issue_type,
      :retour_test,
      :status
    )
  end

  def define_issue
    @issue = Issue.find(params[:id])
    @issue_owner = Owner.find_by(params[:current_user])
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_addform.html.erb
<div class="container">
  <%= simple_form_for @issue do |f| %>
    <div class="row">
      <div class="col-sm-4">
        <%= f.input :jiraid, label: 'JIRA ID' %>
      </div>
      <div class="col-sm-4">
        <%= f.association :owner, label: 'Assignee', selected: current_user.id, as: :select %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-3">
        <%= f.input :issue_type, label: 'Type', collection: IssueType.all, label_method: :name, value_method: :name, as: :select %>
      </div>
      <div class="col-sm-2 d-flex align-items-center">
        <div class="custom-control custom-switch">
          <%= f.check_box :retour_test, class: "custom-control-input", id: "customSwitch1" %>
          <label class="custom-control-label" for="customSwitch1"> <i class="bi bi-bug" style="font-size: 1.15rem;"></i> Retour tests </label>
        </div>
      </div>
    </div>
    <br/>
    <br/>
    <div class="row">
      <div class="col-sm-3">
        <%= f.hidden_field :project_id, value: @api_project_name%>
        <%= f.hidden_field :status, value: @api_status%>
        <%= f.hidden_field :time_real, value: @api_time_real%>
        <%= f.hidden_field :time_forecast, value: @api_time_estimate %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/issues/_issue_details_from_jira.html.erb
<h2>Local Jira ID: <%= @issue.jiraid %> | JIRA API ID: <%= @api_issuekey %></h2>
<p>Project name: <%= @api_project_name %></p>
<p>Creation Date: <%= @api_date_created %></p>
<p>Assigned to: <%= @api_display_name %></p>
<p>Status: <%= @api_status %></p>
<p>Creator: <%= @api_issue_creator %></p>
<p>Time Estimate: <%= @issue.time_forecast %> hours </p>
<p>Time Spent: <%= @issue.time_real %> hours</p>
<p>Issue details: <%= @api_summary %></p>

app/views/issues/edit.html.erb
<div class="container">
  <h1 class="display-5"> Edit issue information</h1>
  <%= simple_form_for @issue do |f| %>
    <div class="row">
      <div class="col-sm-4">
        <%= f.input :jiraid, label: 'JIRA ID' %>
      </div>
      <div class="col-sm-4">
        <%= f.association :owner, label: 'Assignee', selected: current_user.id, as: :select %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-3">
        <%= f.input :issue_type, label: 'Type', collection: IssueType.all, label_method: :name, value_method: :name, as: :select %>
      </div>
      <div class="col-sm-2 d-flex align-items-center">
        <div class="custom-control custom-switch">
          <%= f.check_box :retour_test, class: "custom-control-input", id: "customSwitch1" %>
          <label class="custom-control-label" for="customSwitch1"> <i class="bi bi-bug" style="font-size: 1.15rem;"></i> Retour tests </label>
        </div>
      </div>
    </div>
    <br/>
    <br/>
    <div class="row">
      <div class="col-sm-3">
        <%= f.hidden_field :project_id, value: @api_project_name%>
        <%= f.hidden_field :status, value: @api_status%>
        <%= f.hidden_field :time_real, value: @api_time_real%>
        <%= f.hidden_field :time_forecast, value: @api_time_estimate %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/issues/index.html.erb
<br/>
<% if current_user.admin == true %>
  <%= link_to new_issue_path do %>
    <button type="button" class="btn btn-success btn-lg btn-block">Add a new Issue</button>
  <% end %>
<% end %>
<br/>
<div class="table-responsive">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Ticket ID</th>
        <th scope="col">Projet</th>
        <th scope="col">Ressource</th>
        <th scope="col">Type</th>
        <th scope="col">Estimation</th>
        <th scope="col">Réel</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @issues.each do |issue| %>
        <tr>
          <td align="middle"><%= link_to '<i class="bi bi-eye-fill" style="font-size: 1.15rem;""></i>'.html_safe, issue %>
            &nbsp;
            <% if issue.retour_test %>
              <%= '<i class="bi bi-bug" style="font-size: 1.15rem;""></i>'.html_safe %>
            <% else %>
              <%= '<i class="bi bi-hammer" style="font-size: 1.15rem;""></i>'.html_safe %>
            <% end %>
          </td>
          <td><%= issue.jiraid %></td>
          <% if current_user.admin == true %>
            <td><%= link_to issue.project.name, issue.project %></td>
          <% else %>
            <td><%= issue.project.name %></td>
          <% end %>
          <td><%= link_to issue.owner.name, issue.owner %></td>
          <td><%= issue.issue_type %></td>
          <td><%= issue.time_forecast %></td>
          <td><%= issue.time_real %></td>
          <% if current_user.admin == true %>
            <td>
              <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_issue_path(issue) %>
              <%= link_to '<i class="bi bi-trash3"></i>'.html_safe, issue_path(issue), method: :delete %>
            </td>
          </div>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div align="right" style="font-size: 80%"><%= page_entries_info @issues, entry_name: 'issue' %></div>
<span class="d-flex flex-row-reverse"><%= link_to_next_page @issues, 'Next' %>&nbsp;&nbsp;<%= link_to_previous_page @issues, 'Previous' %></span>

app/views/issues/new.html.erb
<h1 class="display-5">Add a new issue by filling its information</h1>
<%= render "addform" %>

app/views/issues/search.html.erb
<br/>
<br/>
<div class="table-responsive">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Ticket ID</th>
        <th scope="col">Projet</th>
        <th scope="col">Ressource</th>
        <th scope="col">Type</th>
        <th scope="col">Estimation</th>
        <th scope="col">Réel</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |issue| %>
        <tr>
          <td align="middle"><%= link_to '<i class="bi bi-eye-fill" style="font-size: 1.15rem;""></i>'.html_safe, issue %>
            &nbsp;
            <% if issue.retour_test %>
              <%= '<i class="bi bi-bug" style="font-size: 1.15rem;""></i>'.html_safe %>
            <% else %>
              <%= '<i class="bi bi-hammer" style="font-size: 1.15rem;""></i>'.html_safe %>
            <% end %>
          </td>
          <td><%= issue.jiraid %></td>
          <td><%= link_to issue.project.name, issue.project %></td>
          <td><%= link_to issue.owner.name, issue.owner %></td>
          <td><%= issue.issue_type %></td>
          <td><%= issue.time_forecast %></td>
          <td><%= issue.time_real %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div align="right" style="font-size: 80%"><%= page_entries_info @results, entry_name: 'issue' %></div>
  <span class="d-flex flex-row-reverse"><%= link_to_next_page @results, 'Next' %>&nbsp;&nbsp;<%= link_to_previous_page @results, 'Previous' %></span>
</div>

app/views/issues/show.html.erb
<h1>Ticket/Issue details</h1>
<div class="table-responsive">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Ticket ID</th>
        <th scope="col">Projet</th>
        <th scope="col">Ressource</th>
        <th scope="col">Type</th>
        <th scope="col">Estimation</th>
        <th scope="col">Réel</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td align="middle"><% if @issue.retour_test %>
            <%= '<i class="bi bi-bug" style="font-size: 1.15rem;""></i>'.html_safe %>
          <% else %>
            <%= '<i class="bi bi-hammer" style="font-size: 1.15rem;""></i>'.html_safe %>
          <% end %></td>
        <td><%= @issue.jiraid %></td>
        <td><%= link_to @issue.project.name, @issue.project %></td>
        <td><%= link_to @issue.owner.name, @issue.owner %></td>
        <td><%= @issue.issue_type %></td>
        <td><%= @issue.time_forecast %></td>
        <td><%= @issue.time_real %></td>
        <% if current_user.admin == true %>
          <td><%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_issue_path(@issue) %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>
<div>
  <%= render "issue_details_from_jira" %>
</div>