config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'issues#search'
  get '/home/jira', to: 'home#jira'
  get '/dailyreports/owner_dailyreport/:id', to: 'dailyreports#owner_dailyreport', :as => 'my_crs'

  resources :projects
  resources :issues
  resources :issue_types
  resources :owners
  resources :dailyreports

  # Devise routes
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  devise_for :users
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in')
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :issues

  before_create { |project| project.jiraid = project.jiraid.upcase }
  before_create { |project| project.name = project.name.titleize }

  validates :jiraid, :name, uniqueness: true
  validates :jiraid, format: { with:/\A[a-zA-Z\d]{2,6}\z/, message: "must follow this format az-AZ" }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :admin_only_access
  before_action :admin_only_access, only: [:new, :create, :destroy, :edit, :update]

  def index
    @projects = Project.all.order(created_at: :desc).page params[:page]
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    define_owner
  end

  def show
    define_owner
    @total_estimation = 0
    @total_real = 0
    @total_tasks = 0
    @total_tasks_duration = 0
    @total_meetings = 0
    @total_meetings_duration = 0
    @total_trainings = 0
    @total_trainings_duration = 0
    @project.issues.each do |issue|
      @total_estimation += issue.time_forecast
      @total_real += issue.time_real
      case issue.issue_type
      when 'Task'
        @total_tasks += 1
        @total_tasks_duration += issue.time_real
      when 'Meeting'
        @total_meetings += 1
        @total_meetings_duration += issue.time_real
      when 'Training', 'Self-training'
        @total_trainings += 1
        @total_trainings_duration += issue.time_real
      end
    end
  end

  def update
    define_owner
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    define_owner
    if current_user.admin?
      @project = Project.find(params[:id])
      @project.destroy
    else
      flash.alert = 'Admin access only'
    end
    previous_page
  end

  private

  def project_params
    params.require(:project).permit(:name, :jiraid, :link)
  end

  def define_owner
    @project = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_addform.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :jiraid, label: 'Enter the JIRA ID', error: 'The JIRA ID is mandatory, please specify one'%>
  <%= f.input :name, label: 'Enter the project name', error: 'The name is mandatory, please specify one'%>
  <%= f.button :submit %>
<% end %>

app/views/projects/edit.html.erb
<h1 class="display-5">Edit project information</h1>
<%= render "addform" %>

app/views/projects/index.html.erb
<h2>Projects List</h2>
<br/>
<br/>
<div class="table-responsive">
  <table class="table table-sm table-hover table-justified">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Jira ID</th>
        <th scope="col">Name</th>
        <th scope="col">Lead</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td align="middle"><%= link_to '<i class="bi bi-eye-fill" style="font-size: 1.15rem;""></i>'.html_safe, project %></td>
          <td><%= project.jiraid %></td>
          <td><%= project.name %></td>
          <td><%= project.lead %></td>
          <% if current_user.admin? %>
            <td align="middle">
              <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_project_path(project) %>
              &nbsp;
              <%= link_to '<i class="bi bi-trash3"></i>'.html_safe, project_path(project), method: :delete, class: "delete-button" %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div align="right" style="font-size: 80%"><%= page_entries_info @projects, entry_name: 'project' %></div>
  <span class="d-flex flex-row-reverse"><%= link_to_next_page @projects, 'Next' %>&nbsp;&nbsp;<%= link_to_previous_page @projects, 'Previous' %></span>
</div>
<br/>
<br/>
<%= link_to new_project_path do %>
  <button type="button" class="btn btn-success btn-lg btn-block">Add a new Project</button>
<% end %>

app/views/projects/new.html.erb
<h1 class="display-5">Add a new project by filling its information</h1>
<%= render "addform" %>

app/views/projects/show.html.erb
<h2><%= @project.name %> - Dashboard</h2>
<br/>
<div class="d-flex justify-content-around">
  <div align="middle" class="card" style="width: 12rem;">
    <div class="card-body">
      <h5 class="card-title">Nombre de Tickets</h5>
      <p class="card-text"><%= @project.issues.count %></p>
    </div>
  </div>
  <div align="middle" class="card" style="width: 12rem;">
    <div class="card-body">
      <h5 class="card-title">Total Estimation</h5>
      <p class="card-text"><%= @total_estimation %> hours</p>
    </div>
  </div>
  <div align="middle" class="card" style="width: 12rem;">
    <div class="card-body">
      <h5 class="card-title">Total Réel</h5>
      <p class="card-text"><%= @total_real %> hours</p>
    </div>
  </div>
  <div align="middle" class="card" style="width: 12rem;">
    <div class="card-body">
      <h5 class="card-title">E/R difference</h5>
      <p class="card-text"><%= @total_estimation - @total_real%> hours</p>
    </div>
  </div>
</div>
<br>
<div class="d-flex justify-content-around">
  <div align="middle" class="card" style="width: 15rem;">
    <div class="card-body">
      <h5 class="card-title"># of Tasks: <%= @total_tasks %></h5>
      <p class="card-text"><%= @total_tasks_duration %> hours</p>
    </div>
  </div>
  <div align="middle" class="card" style="width: 15rem;">
    <div class="card-body">
      <h5 class="card-title"># of meetings: <%= @total_meetings %></h5>
      <p class="card-text"><%= @total_meetings_duration %> hours</p>
    </div>
  </div>
  <div align="middle" class="card" style="width: 15rem;">
    <div class="card-body">
      <h5 class="card-title"># of trainings: <%= @total_trainings %></h5>
      <p class="card-text"><%= @total_trainings_duration %> hours</p>
    </div>
  </div>
</div>
<br/>
<br/>
<h4>Issues from <%= @project.name %></h4>
<div class="table-responsive">
  <table class="table table-sm table-hover table-justified">
    <thead>
      <tr>
        <th scope="col">Jira ID</th>
        <th scope="col">Owner</th>
        <th scope="col">Type</th>
        <th scope="col">Estimation</th>
        <th scope="col">Réel</th>
      </tr>
    </thead>
    <tbody>
      <% @project.issues.each do |issue| %>
        <tr>
          <td>
            <%= link_to issue.jiraid, issue %>
            &nbsp;
            <% if issue.retour_test %>
              <%= '<i class="bi bi-bug" style="font-size: 1.15rem;""></i>'.html_safe %>
            <% else %>
              <%= '<i class="bi bi-hammer" style="font-size: 1.15rem;""></i>'.html_safe %>
            <% end %>
          </td>
          <td><%= link_to issue.owner.name, issue.owner%></td>
          <td><%= issue.issue_type %></td>
          <td><%= issue.time_forecast %></td>
          <td><%= issue.time_real %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>