config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'issues#search'
  get '/home/jira', to: 'home#jira'
  get '/dailyreports/owner_dailyreport/:id', to: 'dailyreports#owner_dailyreport', :as => 'my_crs'

  resources :projects
  resources :issues
  resources :issue_types
  resources :owners
  resources :dailyreports

  # Devise routes
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  devise_for :users
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in')
end

app/models/dailyreport.rb
class Dailyreport < ApplicationRecord
  max_paginates_per 9
  belongs_to :owner
  has_many :dailyreport_issues, dependent: :destroy
  has_many :issues, through: :dailyreport_issues
  accepts_nested_attributes_for :issues, allow_destroy: true

end

app/controllers/dailyreports_controller.rb
class DailyreportsController < ApplicationController
  helper DailyreportsHelper
  before_action :define_dailyreport, only: [:edit, :show, :update, :destroy]

  def index
    @dailyreports = Dailyreport.all.order(created_at: :desc).page params[:page]
  end

  def new
    @dailyreport = Dailyreport.new
    @dailyreport.issues.build
    @issues = Issue.all.order(created_at: :desc)
  end

  def edit
  end

  def show
  end

  def owner_dailyreport
    @owner_dailyreport = current_user.owner.dailyreports
  end

  def create
    @dailyreport = Dailyreport.new(dailyreport_params)

    @dailyreport.issues.each do |cr_issue|
      call_jira_api("https://agenceinspire.atlassian.net/rest/api/3/issue/#{cr_issue.jiraid}")
      issue_details_from_jira(cr_issue)

      next unless issue_time_real_from_jira(cr_issue)
    end

    if @dailyreport.save
      redirect_to @dailyreport, notice: 'Dailyreport was successfully created.'
    else
      render :new
    end
  end

  def update
    if @dailyreport.update(dailyreport_params)
      redirect_to @dailyreport, notice: 'Dailyreport was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if current_user.admin? || current_user.email == @dailyreport.owner.email
      @dailyreport.destroy
    else
      admin_only_access
    end
    previous_page
  end

  private

  def dailyreport_params
    params.require(:dailyreport).permit(
      :comment,
      :owner_id,
      issues_attributes: [
        :jiraid,
        :project_id,
        :owner_id,
        :time_forecast,
        :time_real,
        :issue_type,
        :retour_test,
        :status,
        :_destroy
      ]
    )
  end

  def define_dailyreport
    @dailyreport = Dailyreport.find(params[:id])
  end
end

app/helpers/dailyreports_helper.rb
module DailyreportsHelper

  def status_icon(status)
    case status
    when "Done"
      "<i class='bi bi-check-all'></i>".html_safe
    when "Réalisé"
      "<i class='bi bi-check-all'></i>".html_safe
    when "Archived"
      "<i class='bi bi-archive'></i>".html_safe
    when 'In Progress'
      "<i class='bi bi-gear-wide-connected'></i>".html_safe
    when "On Hold"
      "<i class='bi bi-hourglass'></i>".html_safe
    else
      "<i class='bi bi-question'></i>".html_safe
    end
  end

  def type_issue_icon(type_issue)
    case type_issue
    when "Training"
      "<i class='bi bi-book-half'></i>".html_safe
    when "Meeting"
      "<i class='bi bi-calendar-week'></i>".html_safe
    end
  end
end

app/views/dailyreports/_addform.html.erb
<%= simple_form_for @dailyreport do |f| %>
  <h4><%= DateTime.now.strftime("%d/%m/%Y %H:%M")%></h4>
  <%= f.association :owner, selected: current_user.id %>
  <h2>Tasks</h2>
  <%= f.simple_fields_for :issues do |issue| %>
    <%= render 'issue_fields', :f => issue %>
  <% end %>
  <br/>
  <div class='links'  align="right">
    <%= link_to_add_association 'Add a task <i class="bi bi-plus-square-fill"></i>'.html_safe, f, :issues %>
  </div>
  <h3>Other issues:</h3>
  <%= f.input :comment %>
  <br/>
  <%= f.submit  'Create CR' %>
<% end %>

app/views/dailyreports/_issue_fields.html.erb
  <hr>
<div class='nested-fields d-flex'>
  <div class="col-sm-2 mr-3">
    <%= f.input :jiraid, label: 'JIRA ID' %>
  </div>
  <div class="col-sm-4 mr-3">
    <%= f.association :owner, label: 'Assignee', selected: current_user.id, as: :select %>
  </div>
  <div class="col-sm-3 mr-3">
    <%= f.input :issue_type, label: 'Type', collection: IssueType.all, label_method: :name, value_method: :name, as: :select %>
  </div>
  <div class="col-sm-2 d-flex align-items-center">
    <div class="custom-control custom-switch">
      <%= f.check_box :retour_test, class: "custom-control-input", id: "customSwitch1" %>
      <label class="custom-control-label" for="customSwitch1"> <i class="bi bi-bug" style="font-size: 1.15rem;"></i> Retour tests </label>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3">
      <%= f.hidden_field :project_id, value: @api_project_name %>
      <%= f.hidden_field :status, value: @api_status %>
      <%= f.hidden_field :time_real, value: @api_time_real %>
      <%= f.hidden_field :time_forecast, value: @api_time_estimate %>
    </div>
  </div>
</div>
<div align="right" class="ml-auto">
  <%= link_to_remove_association 'Remove this task <i class="bi bi-dash-square"></i>'.html_safe, f %>
</div>

app/views/dailyreports/_issues_fields.html.erb
<div class="issues_fields">
  <div class="form-row">
    <div class="form-group col-sm-2">
      <%= f.input :jiraid, placeholder: "EXP-100", label: 'JIRA ID', class: "form-control form-control-sm" %>
    </div>
    <div class="form-group col-sm-2">
      <%= f.association :project, placeholder: "Project X", label_method: :jiraid, value_method: :id, class: "form-control form-control-sm" %>
    </div>
    <div class="form-group col-sm-2">
      <%= f.association :owner, selected: f.object.owner, label: 'Owner', class: "form-control form-control-sm"%>
    </div>
    <div class="form-group col-sm-3">
      <%= f.input :departement, collection: Departement.all, label: 'Dept.', class: "form-control form-control-sm" %>
    </div>
    <div class="form-group col-sm-1">
      <%= f.input :time_forecast, label: 'Estimated',placeholder: '60min', class: "form-control form-control-sm" %>
    </div>
    <div class="form-group col-sm-1">
      <%= f.input :time_real, label: 'Real', placeholder: '80min', class: "form-control form-control-sm" %>
    </div>
    <div class="custom-control custom-switch">
      <%= f.check_box :retour_test, class: "custom-control-input", id: "customSwitch1" %>
      <label class="custom-control-label" for="customSwitch1"> <i class="bi bi-bug" style="font-size: 1.15rem;"></i> Retour Test </label>
    </div>
  </div>
  <div class="form-group controls-issue-container" , align="right" >
    <%= link_to "-", "#", class:"btn btn-danger btn-sm-2 remove-issue" %>
    <div class="form-group" , align="right" >
      <%= link_to "+", "#", class: "btn btn-success btn-sm-2 add-issue"%>
    </div>
  </div>
</div>
<script>
  var id = 0;
    $(document).on('click', '.add-issue', function() {
      id++;
      var issueFields = $('.issues_fields:first').clone();
      issueFields.find('input').val('');
      issueFields.attr("data-id", id);
      issueFields.insertAfter('.issues_fields:last');
    });

    $(document).on('click', '.remove-issue', function() {
      $(this).closest('.issues_fields').remove();
    });
</script>

app/views/dailyreports/edit.html.erb
<h1 class="display-5">Edit report</h1>
<%= render "addform" %>

app/views/dailyreports/index.html.erb
<h3>Inspire Production Team CRs</h3>
<br>
<%= link_to new_dailyreport_path do %>
  <button type="button" class="btn btn-success btn-sm btn-block">Submit a CR</button>
<% end %>
<br>
<div class="d-flex flex-wrap">
  <!-- Header of the card -->
  <% @dailyreports.each do |dailyreport| %>
    <div class="card" style="width: 45%; margin:10px">
      <div class="card-body">
        <h6 class="card-title d-flex justify-content-between">
          #CR: <%= dailyreport.id %> du <%= dailyreport.created_at.strftime("%d %B %Y - %kh%M") %>
          <% if current_user.admin? %>
            <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_dailyreport_path(dailyreport)%>
          <% end %>
        </h6>
        <h5 class="card-subtitle mb-2 text-muted">Owner: <%= link_to dailyreport.owner.name, dailyreport.owner %></h5>
        <hr/>
        <!-- Main Tasks -->
        <% if dailyreport.issues == [] %>
          <p class="card-text"> No Tickets in this CR </p>
        <% else %>
          <h6><strong> Main Tasks:</strong> </h6>
          <% dailyreport.issues.each do |issue| %>
            <% if issue.issue_type == "Task" %>
              <span class="card-text"> <%= status_icon(issue.status) %> </span>
              &nbsp;
              <span class="card-text" style="font-weight: bolder;">  <%= link_to issue.jiraid, issue %></span>
              <span class="card-text">  Time spent: <%= issue.time_real %> min - </span>
              <span class="card-text">  <%= issue.status %></span><br>
            <% end %>
          <% end %>
          <!-- Other tasks -->
          <h6><strong> Other Tasks: </strong></h6>
          <% dailyreport.issues.each do |issue| %>
            <% if issue.issue_type != "Task" %>
              <span class="card-text"> <%= type_issue_icon(issue.issue_type) %> </span>              &nbsp;
              <span class="card-text" style="font-weight: bolder;">  <%= link_to issue.jiraid, issue %></span>
              <span class="card-text">  <%= issue.issue_type %></span>
              <span class="card-text">  Time spent: <%= issue.time_real %> min - </span>
              <span class="card-text">  <%= issue.status %></span><br>
            <% end %>
          <% end %>
        <% end %>
        <!-- Comments -->
        <div>
          <% if dailyreport.comment.nil? || dailyreport.comment == "" %>
          <% else %>
            <p class="card-text" style="font-weight: light;"><strong>Commentaires:</strong> <%= dailyreport.comment %> </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<br>
<div align="right" style="font-size: 80%"><%= page_entries_info @dailyreports, entry_name: 'CRs' %></div>
<div class="d-flex flex-row-reverse">
  <%= link_to_next_page @dailyreports, 'Next' %>&nbsp;&nbsp;
  <%= link_to_previous_page @dailyreports, 'Previous' %>
</div>

app/views/dailyreports/new.html.erb
<h1 class="display-5">Add a new report by filling its information</h1>
<%= render "addform" %>

app/views/dailyreports/owner_dailyreport.html.erb
<h3><%= "#CRs signed by #{current_user.owner.name}" %></h3>
<%= link_to new_dailyreport_path do %>
  <button type="button" class="btn btn-success btn-sm btn-block">Submit a CR</button>
<% end %>
<div class="d-flex flex-wrap">
  <% @owner_dailyreport.each do |dailyreport| %>
    <div class="card" style="width: 45%; margin:10px">
      <div class="card-body">
        <h3 class="card-title">#CR: <%= dailyreport.id %> du <%= dailyreport.created_at.strftime("%d %B %Y - %kh%M") %></h3>
        <hr/>
        <!-- Main Tasks -->
        <% if dailyreport.issues == [] %>
          <p class="card-text"> No Tickets in this CR </p>
        <% else %>
          <h6><strong> Main Tasks:</strong> </h6>
          <% dailyreport.issues.each do |issue| %>
            <% if issue.issue_type == "Task" %>
              <span class="card-text"> <%= status_icon(issue.status) %> </span>
              &nbsp;
              <span class="card-text" style="font-weight: bolder;">  <%= link_to issue.jiraid, issue %></span>
              <span class="card-text">  Time spent: <%= issue.time_real %> min - </span>
              <span class="card-text">  <%= issue.status %></span><br>
            <% end %>
          <% end %>
          <!-- Other tasks -->
          <h6><strong> Other Tasks: </strong></h6>
          <% dailyreport.issues.each do |issue| %>
            <% if issue.issue_type != "Task" %>
              <span class="card-text"> <%= type_issue_icon(issue.issue_type) %> </span>              &nbsp;
              <span class="card-text" style="font-weight: bolder;">  <%= link_to issue.jiraid, issue %></span>
              <span class="card-text">  <%= issue.issue_type %></span>
              <span class="card-text">  Time spent: <%= issue.time_real %> min - </span>
              <span class="card-text">  <%= issue.status %></span><br>
            <% end %>
          <% end %>
        <% end %>
        <!-- Comments -->
        <div>
          <% if dailyreport.comment.nil? || dailyreport.comment == "" %>
          <% else %>
            <p class="card-text" style="font-weight: light;"><strong>Commentaires:</strong> <%= dailyreport.comment %> </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/dailyreports/show.html.erb
<div>
  <div class="d-flex" style="justify-content: space-between;">
    <div>
      <h2><%= @owner.name %><% if current_user.email == @owner.user.email %></h2>
        <%= link_to 'My Dailyreports', my_crs_path(id: @owner.id), class:"btn btn-dark" %>
      </div>
      <div align="right">
        <%= link_to 'Update my profile details', edit_owner_path(@owner), type:"button", class:"btn btn-light" %></h2>
      <%= link_to 'Update my password', edit_user_registration_path, type:"button", class:"btn btn-light" %></h2>
  </div>
</div>
<% end %>
<br/>
<h3><%= "#CR: #{@dailyreport.id} du #{@dailyreport.created_at.strftime("%d %B %Y - %kh%M") }" %></h3>
<div class="card" style="width: 50%;">
  <div class="card-body">
    <h6 class="card-title d-flex justify-content-between">
      #CR: <%= @dailyreport.id %> du <%= @dailyreport.created_at.strftime("%d %B %Y - %kh%M") %>
    </h6>
    <h6 class="card-subtitle mb-2 text-muted">Owner: <%= link_to @dailyreport.owner.name, @dailyreport.owner %></h6>
    <hr/>
    <!-- Main Tasks -->
    <% if @dailyreport.issues == [] %>
      <p class="card-text"> No Tickets in this CR </p>
    <% else %>
      <h6><strong> Main Tasks:</strong> </h6>
      <% @dailyreport.issues.each do |issue| %>
        <% if issue.issue_type == "Task" %>
          <span class="card-text"> <%= status_icon(issue.status) %> </span>
          &nbsp;
          <span class="card-text" style="font-weight: bolder;">  <%= link_to issue.jiraid, issue %></span>
          <span class="card-text">  Time spent: <%= issue.time_real %> min - </span>
          <span class="card-text">  <%= issue.status %></span><br>
        <% end %>
      <% end %>
      <!-- Other tasks -->
      <h6><strong> Other Tasks: </strong></h6>
      <% @dailyreport.issues.each do |issue| %>
        <% if issue.issue_type != "Task" %>
          <span class="card-text"> <%= type_issue_icon(issue.issue_type) %> </span>
          &nbsp;
          <span class="card-text" style="font-weight: bolder;">  <%= link_to issue.jiraid, issue %></span>
          <span class="card-text">  <%= issue.issue_type %> - </span>
          <span class="card-text">  Time spent: <%= issue.time_real %> min - </span>
          <span class="card-text">  <%= issue.status %></span><br>
        <% end %>
      <% end %>
    <% end %>
    <!-- Comments -->
    <div>
      <% if @dailyreport.comment.nil? || @dailyreport.comment == "" %>
      <% else %>
        <p class="card-text" style="font-weight: light;"><strong>Commentaires:</strong> : <%= @dailyreport.comment %> </p>
      <% end %>
    </div>
  </div>
</div>