config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'issues#search'
  get '/home/jira', to: 'home#jira'
  get '/dailyreports/owner_dailyreport/:id', to: 'dailyreports#owner_dailyreport', :as => 'my_crs'

  resources :projects
  resources :issues
  resources :issue_types
  resources :owners
  resources :dailyreports

  # Devise routes
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  devise_for :users
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in')
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg ">
  <div class="container-fluid">
    <%= link_to 'INSPIRE GROUP' , root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Projects', projects_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Daily reports', dailyreports_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "My profile", current_user.owner, class:"nav-link"%>
          </li>
          <% if current_user.admin? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Settings
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to 'Issues Types', issue_types_path, class:"dropdown-item"%>
                <%= link_to 'Team members', owners_path, class:"dropdown-item"%>
                <%= link_to 'Issues', issues_path, class:"dropdown-item"%>
                <%= link_to 'Jira API Test', home_jira_path, class:"dropdown-item"%>
              </div>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, :method => :delete, class:"nav-link" %>
          </li>
        </ul>
      </div>
      <%= form_tag(search_path, :method => "get") do %>
        <div class="input-group">
          <%= search_field_tag :search, params[:search], placeholder: "EG-1, LGK-123, AC-83", class: "form-control" %>
          <div class="input-group-btn">
            <%= button_tag "Search", :class => 'btn btn-success glyphicon glyphicon-search', :jiraid => nil %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
    <title>Issues Tracker</title>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <% if notice %>
        <p class="close alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="close alert alert-danger"><%= alert %></p>
      <% end %>
      <br/>
      <%= yield %>
      <br/>
    </div>
    <!-- Close Alerts Script -->
    <script>
      $(document).ready(function(){
        setTimeout(function() {
          const alerts = document.querySelectorAll('.alert');
          alerts.forEach(function(alert) {
            $(alert).fadeOut(1000, function() {
              $(this).remove();
            });
          });
        }, 2000);
      });
    </script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>